### ISSUE TITLE
Community forum

### ISSUE THREAD

**Issue by bealan** [CANtact/cantact.github.io#1]
I just got my cantact in the mail unexpectedly yesterday after ordering it months ago.  Even tho I do not have much coding experience, I did well in the classes I took in college,  so i figured with the community I could learn what i need to learn to get going with hacking my car.   However, i have found no such promised community.  Theres a dead reddit.com/r/cantact,   the https://discuss.cantact.io/ directory does not seem to exist.  And any google searches are little help as well.

**Comment by ericevenchick** [comment]
Hi bealan,

The forum server went down, but it's back up at https://discuss.cantact.io now. Sorry about that.

Docs articles are all here: https://discuss.cantact.io/c/docs. More are on the way. Feel free to ask questions over there :)

Thanks,
Eric
